GET http://localhost:3000/orders/account HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NDA2NGFlYzU2Y2NiODg5OGViZDMwMyIsInJvbGUiOiJjdXN0b21lciIsImlhdCI6MTc1MjI0MzQ5MSwiZXhwIjoxNzUyODQ4MjkxfQ.PSyagJU2KPk3OcB6sV01PTidi17oMSI6zm6KDafQt-M