DELETE http://localhost:3000/categories/6849a0c8bf580b9b9eeb912d HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NDA1ZDRhYzU2Y2NiODg5OGViZDJmZiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0OTIyNTYxNCwiZXhwIjoxNzQ5ODMwNDE0fQ.OW7bG8MLhqbLab2NV5VdUQioB29gOsrrK5Z7VUhcrQk