GET http://localhost:3000/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NDA1ZDRhYzU2Y2NiODg5OGViZDJmZiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc0OTIyNTYxNCwiZXhwIjoxNzQ5ODMwNDE0fQ.OW7bG8MLhqbLab2NV5VdUQioB29gOsrrK5Z7VUhcrQk