GET http://localhost:3000/users HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NDA1ZDRhYzU2Y2NiODg5OGViZDJmZiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTg5NDUxNCwiZXhwIjoxNzUyNDk5MzE0fQ.9c3y0cPz_IRtGUTK1AlBr9JolGEZNdNSUJT7oFtYKmY