DELETE http://localhost:3000/products/685030c2ea736b30b1c0c218 HTTP/1.1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NDA1ZDRhYzU2Y2NiODg5OGViZDJmZiIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc1MTg5NDUxNCwiZXhwIjoxNzUyNDk5MzE0fQ.9c3y0cPz_IRtGUTK1AlBr9JolGEZNdNSUJT7oFtYKmY